array1 = ['Adobe Systems, Inc.', 'Adventist Health', 'AECOM',
          'Aerojet Rockedyne Holdings (GenCorp)',
          'Alameda-Contra Costa Transit District',
          'Alaska Community Foundation',
          'Alaska Retirement Management Board', 'Alexander & Baldwin, Inc.',
          'Allergan, Inc.', 'Alyeska Pipeline Service Company', 'Amazon',
          'American Jewish University', 'Amgen Inc.',
          'Anchorage Police & Fire Retirement System', 'Apple, Inc.',
          'Applied Materials', 'Arizona Community Foundation',
          'Arizona Public Safety Personnel Retirement System',
          'Arizona State Endowment Fund', 'Arizona State Retirement System',
          'Arizona State University Foundation',
          'Arizona State University Managed Operating Funds',
          'Arnold & Mabel Beckman Foundation',
          'Art Center College of Design', 'Asante Health System',
          'ASARCO, LLC',
          'Automobile Club of Southern California (AAA of So Cal)', 'Avaya',
          'Avery Dennison Corporation', 'Avista Corporation', 'Avnet',
          'Ball Corporation', 'Bashas', 'Bechtel', 'Bernalillo County',
          'Blue Shield of California', 'Boise Cascade', 'Boise Inc.',
          'Broadcom (LSI Corporation/ Avago/Broadcom)', 'Cal Poly Pomona',
          'Cal Savinds Plan', 'California Community Foundation',
          'California Healthcare foundation',
          'California Institute of Technology', 'California Savings Plus',
          'California State Teachers Retirement System',
          'California Teachers Association',
          'California Western School of Law', 'Casey Family Programs',
          'Catholic Community Foundation', 'Catholic Health Initiatives',
          'Cedars-Sinai Medical Center',
          'CenturyLink (Qwest) Asset Management/Centurylink',
          'CH2M HILL, Inc.', 'Chapman University',
          'Charles & Helen Schwab Foundation', 'Chevron Corporation',
          'Childrens Hospital & Research Center at Oakland',
          'Childrens Hospital Central California',
          'Childrens Hospital of Los Angeles', 'Cisco Systems, Inc.',
          'City of Hope & Affiliates',
          'City of San Jose Retirement Services Department',
          'Cliveden/B Chew', 'Clorox Co.', 'Colburn Music Fund',
          'Commonsense Investment',
          'Community Hospital Association (Boulder Community Hospital Foundation)',
          'Community Hospital of the Monterey Peninsula',
          'Contra Costa County Employees Retirement Association', 'Costco',
          'County of Los Angeles Deferred Compensation Program',
          'Cubic Corp.',
          'Daughters of Charity Foundation, Province of the West',
          'DaVita HealthCare Partners Inc.', 'Del Monte Corp.',
          'Denver Board of Water Commissioners',
          'Deseret Mutual Benefit Administration',
          'Dignity Health (Catholic Healthcare West)', 'Diocese of Oakland',
          'Duffield Family Foundation', 'East Bay Community Foundation',
          'ebay', 'Eisenhower Medical Center',
          'Electric Power Research Institute',
          'Farmers Insurance Group, Inc.', 'First Data Corporation',
          'Fortive', 'Foster Farms', 'Freeport-McMoRan Copper & Gold Inc.',
          'Fujitsu America, Inc.', 'GenCorp', 'Genentech, Inc.',
          'General Atomics', 'Google',
          'Gordon E. & Betty I. Moore Foundation',
          'Great-West Life & Annuity Insurance Company',
          'Great-West Life & Annuity Insurance Company/EMPOWER',
          'Group Health Cooperative', 'H.N. & Frances C. Berger Foundation',
          'Hawaii DC', 'Hawaii Pacific Health',
          'Henry J. Kaiser Family Foundation',
          'Hewlett Packard Company (HP)',
          'Hoag Memorial Hospital Presbyterian', 'Idaho National Laboratory',
          'Idaho Power Co.', 'Industrial commission of arizona',
          'Ingram Micro', 'Intel Corp.', 'Intermountain Health Care, Inc.',
          'Intuit Inc.', 'J.R. Simplot Company', 'Jack in the Box, Inc.',
          'Jacobs Engineering', 'John Muir Mount Diablo Health System',
          'Kaiser Aluminum Corporation', 'Kaiser Permanente',
          'Kemper and Ethel Marley Foundation', 'Koch Industries',
          'Loma Linda University Adventist Health Sciences Center',
          'Longview Fibre Paper & Packaging, Inc.',
          'Los Angeles City Employees Retirement System (LACERS)',
          'Loyola Marymount University',
          'LSI Corporation/ acqujired by Avago/acquired by Broadcom',
          'Lucile Salter Packard Childrens Hospital at Stanford',
          'M.J. Murdock Charitable Trust', 'Makena ',
          'Marguerite Casey Foundation',
          'Maricopa County Community College District', 'Mattel',
          'McClatchy Company', 'McKesson Corporation', 'MedAmerica, Inc.',
          'Memorial Health Services', 'Mentor Graphics',
          'Meyer Memorial Trust', 'Micron Technology, Inc.', 'Microsoft',
          'Milliman',
          'Modesto Irrigation District Employees Retirement System',
          'Molson Coors Brewing Company', 'Montana University System',
          'National University', 'Navajo Nation', 'Nevada DC', 'Nike',
          'Nordstrom', 'Northrop Grumman Corporation',
          'Northwest Natural Gas Co.', 'NV Energy', 'Occidental College',
          "O'Melveny & Myers LLP", 'Oracle',
          'Oregon Public Employees Retirement Fund',
          'Oregon State University Foundation', 'Orthopaedic Hospital',
          'PAAMCO', 'PACCAR, Inc.', 'Pacific Life Insurance Company',
          'PacifiCorp', 'Palomar Pomerado Health', 'Parsons Corporation',
          'Pasadena Hospital Association', 'PeaceHealth', 'PG&E Corporation',
          'Pinnacle West Capital Corporation',
          'Plum Creek Timber Company, Inc.', 'Potlatch Corporation',
          'Poudre Valley Health Care, Inc. & Affiliates',
          'Precision Castparts Corp.', 'Premera Blue Cross', 'Presbytherian',
          'Puget Sound Energy, Inc.', 'QEP', 'Qualcomm, Inc.', 'QueensCare',
          'Questar Corporation', "Raley's Supermarkets, Inc.",
          'Rasmuson Foundation/Latash',
          'Roman Catholic Diocese of Boise (Idaho Catholic Foundation)',
          'Sacramento City Employees Retirement System',
          'Sacramento County Transit', 'Safeway, Inc.', 'Salem Hospital',
          'Salt Lake City Corporation', 'San Diego Union - Tribune',
          'San Francisco DC Plan', 'San Francisco Foundation',
          'San Manuel Band of Mission Indians',
          'Sandia National Laboratories', 'Santa Barbara Cottage Hospital',
          'Santa Clara University', 'Scottsdale Healthcare Corp.',
          'Scripps Health', 'Seagate Technology, Inc.',
          "Seattle Children's Hospital", 'Seattle Times Co.',
          'Sempra Energy', 'Sharp HealthCare Corporation',
          'sheridan college', 'Simpson Investment Company',
          'Skoll Foundation', 'Snoqualmie Tribe',
          'Soka University of America', 'Southern California Edison Company',
          'Southwest Gas Corporation', 'SRI International',
          'St. Joseph Health System', 'Stanford Hospital & Clinics',
          'Stanford University', 'Starbucks', 'Sutter Health',
          'Symantec Corporation', 'Teledyne Technologies',
          'The Aerospace Corporation', 'The Anschutz Foundation',
          'The California Endowment', 'The California Wellness Foundation',
          'The Denver Foundation', 'The DIRECTV Group, Inc.',
          'The First American Corporation', 'The Fuller Foundation',
          'The George S. & Dolores Dore Eccles Foundation',
          'The Hawaii Community Foundation',
          'The Idaho Endowment Fund Investment Board',
          'The McConnell Foundation', 'The Oregon Community Foundation',
          'The Queens Health Systems', 'The Ralph M. Parsons Foundation',
          'The Regence Group', 'The Seattle Foundation',
          'The Sierra Club Foundation',
          'The University of California, Davis Foundation',
          'The University of California, Irvine Foundation',
          'The Walt & Lilly Disney Foundation', 'The Walt Disney Co.',
          'Thomas & Dorothy Leavey Foundation',
          'Thomas & Stacey Siebel Foundation/First Virtual Group',
          'T-Mobile US, Inc.', 'Toyota Motor Sales USA, Inc.',
          'UCLA Foundation', 'UniHealth Foundation',
          'UnionBanCal Corporation',
          'University of California, San Diego Foundation',
          'University of Colorado Foundation/Perella Weinburg',
          'University of La Verne',
          'University of New Mexico Foundation, Inc.',
          'University of Puget Sound', 'University of San Diego',
          'University of Southern California (USC)', 'University of Utah',
          'University of Wyoming',
          'Utah School and Institutional Trust Fund',
          'Utah State University', 'Ventura County Community Foundation',
          'Virginia G. Piper Charitable Trust',
          'Virginia Mason Medical Center',
          'Washington State University Foundation', 'Weingart Foundation',
          'Wells Fargo', 'Western Digital',
          'Western Union Financial Services, Inc.', 'Weyerhaeuser Company',
          'Whittier College', 'WRS']

array2 = ['AAA Northern California, Nevada & Utah Auto Exchange',
          'ACCO Engineered Systems', 'Adams County Retirement Plan',
          'Adidas America, Inc.', 'Adobe Systems, Inc.',
          'Advanced Micro Devices, Inc.', 'AECOM Technology Corporation',
          'Aera Energy LLC', 'Aerojet Rocketdyne Holdings, Inc.',
          'Agilent Technologies, Inc.',
          'Alameda County Deferred Compensation Plans',
          'Alameda County Employees Retirement Association',
          'Alameda-Contra Costa Transit District', 'Alaska Airlines, Inc.',
          'Albertsons LLC', 'Allianz of America Corporation',
          'Alphabet Inc.', 'Amazon.com Holdings, Inc.',
          'American Honda Motor Co., Inc.', 'Amgen Inc.',
          'Antelope Valley Health Care District', 'APL Limited',
          'Apollo Education Group, Inc.', 'Apple, Inc.',
          'Applied Materials, Inc.', 'Arapahoe County', 'ARCADIS U.S., Inc.',
          'Archdiocese of Los Angeles', 'Arizona Board of Regents',
          'Arizona Deferred Compensation Committee',
          'Arizona Public Safety Personnel Retirement System',
          'Arizona State Retirement System', 'Arrow Electronics, Inc.',
          'Asante Health System & Subsidiaries', 'ASARCO, LLC',
          'Autodesk, Inc.', 'Autoliv ASP, Inc.',
          'Automobile Club of Southern California', 'Avaya Inc.',
          'Avery Dennison Corporation', 'Avista Corporation', 'Avnet, Inc.',
          'Ball Corporation', 'Bank of Hawaii', 'Banner Health',
          'Bechtel Group, Inc.', 'Billings Clinic',
          'Bio-Rad Laboratories, Inc.', 'Blood Systems, Inc.',
          'Blount International, Inc.', 'Blue Shield of California',
          'Boise Cascade Holdings LLC', 'Boulder Community Health',
          'Broadcom Limited', 'Brocade Communications Systems, Inc.',
          'Cadence Design Systems, Inc.',
          'Caesars Entertainment Corporation',
          'California Casualty Management Co.',
          'California Institute of Technology',
          'California Public Employees Retirement Systems (CalPERS)',
          'California Savings Plus Program',
          'California State Teachers Retirement System (CalSTRS)',
          'California Teachers Association', 'California Water Service Co.',
          'Cambia Health Solutions', 'Carlisle Companies, Inc.',
          'Catholic Health Initiatives', 'CBRE, Inc.',
          'Cedars-Sinai Medical Center', 'CH2M HILL, Inc.',
          'Chevron Corporation', 'Cisco Systems, Inc.',
          'City & County of Denver', 'City & County of Honolulu',
          'City National Bank', 'City of Aurora', 'City of Fort Collins',
          'City of Fresno Retirement Systems',
          'City of Los Angeles Deferred Compensation', 'City of Phoenix',
          'City of Sacramento', 'City of San Diego Deferred Compensation',
          'City of San Jose Retirement Services Department',
          'City of San Jose, Human Resources', 'City of Scottsdale',
          'City of Tacoma', 'Clark County', 'Clearwater Paper Corporation',
          'Colorado County Officials & Employees Retirement Association',
          'Colorado Public Employees Retirement Association',
          'Community Hospital of the Monterey Peninsula',
          'Community Hospitals of Central California', 'Contra Costa County',
          'Contra Costa County Deferred Compensation Plan',
          'Contra Costa County Employees Retirement Association',
          'Cooley, LLP', 'Cooper Companies, Inc.', 'CoorsTek',
          'Costco Wholesale Corporation',
          'County of Los Angeles Deferred Compensation Program',
          'County of Orange',
          'County of Riverside Deferred Compensation Program',
          'County of San Diego Deferred Compensation Program',
          'County of Santa Clara', 'County of Ventura', 'County of Weld',
          'Cubic Corp.', 'Daimler Trucks North America LLC',
          'Davis Wright Tremaine LLP', 'DaVita Inc.', 'DCP Midstream LLC',
          'Del Monte Foods, Inc.', 'Delta Dental of California, Inc.',
          'Denver Board of Water Commissioners',
          'Denver Employees Retirement Plan',
          'Denver Regional Transportation District',
          'Deseret Mutual Benefit Administration', 'Dignity Health',
          'Dole Food Company, Inc.', 'Dyno Nobel, Inc.',
          'E & J Gallo Winery',
          'East Bay Municipal Utility District Employees Retirement System',
          'eBay Incorporated', 'Edwards Lifesciences Corporation',
          'Eisenhower Medical Center', 'El Camino Hospital',
          'El Paso County Pension System', 'Enloe Medical Center',
          'Environmental Systems Research Institute, Inc.',
          'Envision Healthcare', 'ESCO Corp.',
          'Esterline Technologies Corp.', 'Expedia, Inc.',
          'Experian Information Solutions, Inc.', 'Facebook, Inc.',
          'Farmers Insurance Group, Inc.', 'Fenwick & West LLP',
          'Fire & Police Pension Association of Colorado',
          'First American Financial Corporation', 'First Hawaiian, Inc.',
          'Flextronics International, USA Inc.',
          'FlightSafety International Inc.',
          'Forest Lawn Memorial Park Association', 'Fortive Corporation',
          'Foster Farms', 'Franklin Resources, Inc.',
          'Fred Hutchinson Cancer Research Center', 'Freeport-McMoRan Inc.',
          'Fresno County Employees Retirement Association',
          'Fujitsu America, Inc.', 'Gap, Inc.', 'Gates Retirement Board',
          'Gemological Institute of America, Inc.', 'Genentech, Inc.',
          'General Atomics', 'Gensler & Associates',
          'Gibson, Dunn & Crutcher, LLP', 'Gilead Sciences, Inc.',
          'GlobalFoundries U.S. Inc.',
          'Golden Gate Bridge Highway & Transportation District',
          'Golden State Water', 'Good Samaritan Hospital',
          'Government Employees Retirement System of the U.S. Virgin Islands',
          'Great-West Life & Annuity Insurance Company',
          'Grifols Therapeutics, Inc.', 'Hanford Site Multi-Employer Plans',
          'Harrison Medical Center', 'Hawaii Deferred Compensation Fund',
          "Hawaii Employees' Retirement System",
          'Hawaii Employer-Union Health Benefits Trust Fund (EUTF)',
          'Hawaii Pacific Health', 'Hawaiian Airlines, Inc.',
          'Hawaiian Electric Industries, Inc.', 'Healthcare Partners, LLC',
          'Hewlett Packard Enterprise Company',
          'Hitachi Vantara Corporation', 'HonorHealth', 'HP Inc.',
          'Huntsman Corporation', 'Hyundai Motor America',
          'Idaho National Laboratory', 'Idaho Power Company', 'IHS, Inc.',
          'Imperial County Employees Retirement System',
          'Infineon Technologies North America Corp.', 'Intel Corp.',
          'Intermountain Health Care, Inc.',
          'Intermountain Power Service Corp.', 'Intuit Inc.',
          'J. Paul Getty Trust', 'J.R. Simplot Company',
          'Jack in the Box Inc.', 'John Muir Health System',
          'Johns-Manville Corporation', 'Juniper Networks, Inc.',
          'Kaiser Aluminum Corporation', 'Kaiser Permanente',
          'Kamehameha Schools Bishop Estate',
          'Kaweah Delta Health Care District',
          'Kern Community College District',
          "Kern County Employees' Retirement Association",
          'Keysight Technologies, Inc.',
          'King County Deferred Compensation Program', 'KLA-Tencor Corp.',
          'Korn/Ferry International', 'Kyocera International, Inc.',
          'Lam Research Corp.', 'Latham & Watkins LLP',
          'Lawrence Livermore National Security, LLC',
          'Legacy Health System', 'Les Schwab Tire Centers, Inc.',
          'Levi Strauss & Co.', 'Linear Technology Corp.',
          'Los Alamos National Security, LLC',
          'Los Angeles City Employees Retirement System (LACERS)',
          'Los Angeles County Employees Retirement Association (LACERA)',
          'Los Angeles County Metropolitan Transportation Authority',
          'Los Angeles County Museum of Art',
          'Los Angeles Fire & Police Pension System',
          'Los Angeles Philharmonic Association',
          'Los Angeles Unified School District',
          "Los Angeles Water & Power Employees' Retirement Plan",
          'Lucile Salter Packard Childrens Hospital at Stanford',
          'Lynden, Inc.', 'Marin County Deferred Compensation Program',
          'Marin County Employees Retirement Association',
          'Marshall Medical Center', 'Mattel, Inc.',
          'Precision Castparts Corp.', 'Premera Blue Cross',
          'Presbyterian Healthcare Services',
          'Prime Healthcare Services, Inc.', 'Providence St. Joseph Health',
          'Public Employee Retirement System of Idaho',
          'Puget Sound Energy, Inc.', 'Qualcomm, Inc.',
          'Qualstar Credit Union',
          'Quinn, Emanuel, Urquhart & Sullivan, LLP',
          "Rady Children's Hospital & Health Center",
          "Raley's Supermarkets, Inc.", 'RAND Corporation', 'Recology',
          'Recreational Equipment, Inc.', 'Reinalt-Thomas Corp.',
          'Reliance Steel & Aluminum Co.', 'Renown Health System',
          'Republic Services, Inc.',
          'Retirement Plan for Hospital Employees', 'Rogers Corporation',
          'Roseburg Forest Products Co.',
          'Sacramento County Deferred Compensation',
          'Sacramento County Employees Retirement System', 'Safeway Inc.',
          'salesforce.com, inc.',
          'Salinas Valley Memorial Healthcare System', 'Salt River Project',
          'San Antonio Community Hospital', 'San Bernardino County',
          'San Bernardino County Employees Retirement Association',
          'San Diego City Employees Retirement System',
          'San Diego County Employees Retirement Association',
          'San Francisco City & County Employees Retirement System',
          'San Francisco Symphony', 'San Joaquin County',
          'San Joaquin County Employees Retirement Association',
          'San Luis Obispo County',
          'San Mateo County Employees Retirement Association',
          'Sandia National Laboratories', 'Sanmina-SCI Corp.',
          'Santa Barbara Cottage Hospital',
          'Santa Barbara County Employees Retirement System',
          'Santa Clara University',
          'Santa Clara Valley Transportation Authority',
          'Schweitzer Engineering Laboratories, Inc.',
          'Scientific Games Corporation', 'SCL Health', 'Scripps Health',
          'Scripps Research Institute', 'Seagate Technology, Inc.',
          "Seattle Children's Hospital",
          'Seattle City Employees Retirement System',
          'Securitas Security Services USA, Inc.', 'Sempra Energy',
          'Shamrock Foods Co.', 'Sharp HealthCare Corporation',
          'Sheppard, Mullin, Richter & Hampton, LLP',
          'Simpson Investment Company', 'SkyWest, Inc.',
          'Smart & Final, Inc.',
          'Sonoma County Employees Retirement Association',
          'Southern California Edison', 'Southwest Gas Corporation',
          'Spokane Employees Retirement System', 'SRI International',
          "St. Luke's Health System, Ltd.", 'Standard Insurance Company',
          'Stanford Health Care', 'Stanford University',
          'Stanislaus County Employees Retirement Association',
          'Stantec Consulting, Inc.', 'Starbucks Corporation',
          'Sunkist Growers, Inc.', 'Sutter Health & Affiliates',
          'Symantec Corporation', 'Synopsys, Inc.',
          'Teledyne Technologies Incorporated', 'Tetra Tech, Inc.',
          'The Academy of Motion Picture Arts & Sciences',
          'The Aerospace Corporation', 'The Amalgamated Sugar Company, LLC',
          'The California Endowment', 'The Capital Group Companies, Inc.',
          'The Charles Schwab Corporation',
          'The City of Seattle Deferred Compensation Plan',
          'The Clorox Company', 'The Idaho Endowment Fund Investment Board',
          "The Queen's Health Systems", 'The Save Mart Companies',
          'The Walt Disney Co.', 'T-Mobile US, Inc.',
          'Torrance Memorial Medical Center', "Trader Joe's Company",
          'Tri-County Metropolitan Transportation District of Oregon',
          'TriNet HR Corporation', 'Tucson Electric Power Company',
          'Tucson Supplemental Retirement System',
          'Tulare County Employees Retirement Association',
          'Turlock Irrigation District', 'Tutor Perini Corporation',
          "UCSF Benioff Children's Hospital Oakland",
          'U-Haul International, Inc.', 'UMG Recordings, Inc.',
          'United Launch Alliance, LLC',
          'University Corporation for Atmospheric Research',
          'University of California Board of Regents',
          'University of Colorado System', 'University of Denver',
          'University of Southern California', 'University of the Pacific',
          'University of Washington', 'USS-POSCO Industries',
          'Utah State Retirement Systems', 'Utah State University',
          "Valley Children's Healthcare", 'Varian Medical Systems',
          'ViaSat, Inc.', 'Vigilant', 'Virginia Mason Medical Center',
          'Visa, Inc.', 'VMWare, Inc.', 'VSP Global',
          'Washington State Board for Community & Technical Colleges',
          'Washington State Investment Board', 'Wells Fargo & Company',
          'Western Digital Corp.', 'Western Union Financial Services, Inc.',
          'Westmoreland Coal Company', 'Weyerhaeuser Company',
          'Wilbur-Ellis Company', 'WinCo Holdings, Inc.', 'Woodward, Inc.',
          'Wyle Inc.', 'Wyoming Retirement System',
          'Yakima Valley Memorial Hospital Association',
          'Yokohama Tire Corporation', 'Yuma Regional Medical Center',
          'Zions Bancorporation', 'Zoological Society of San Diego']
